---
kind: pipeline
type: docker
name: perl-5-32

steps:
  - name: test
    image: perl:5.32
    environment:
      CODECOV_TOKEN:
        from_secret: codecov-token
    commands:
      - cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Codecov
      - cpanm --quiet --installdeps --notest .
      - perl Makefile.PL
      - make
      - cover -test
      - cover -report codecov

---
kind: pipeline
type: docker
name: perl-5-30

steps:
  - name: test
    image: perl:5.30
    environment:
      CODECOV_TOKEN:
        from_secret: codecov-token
    commands:
      - cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Codecov
      - cpanm --quiet --installdeps --notest .
      - perl Makefile.PL
      - make
      - cover -test
      - cover -report codecov
