--- #YAML:1.0
###########################################################################
#
#   META.yml
#
#   Copyright (C) 1999 Raphael Manfredi.
#   Copyright (C) 2002-2003, 2005, 2013 Mark Rogaski, mrogaski@cpan.org;
#   all rights reserved.
#
#   See the README file included with the
#   distribution for license information.
#
##########################################################################

name:                   Log-Agent
version:                0.307
version_from:           Agent.pm
license:                artistic
distribution_type:      module
installdirs:            site
requires:               
    Tie::Array: 0
recommends:
    Callback: 0
build_requires:
    Test: 0
dynamic_config:         0

