name: CI/CD

on: [push, pull_request]

jobs:

  test:
    name: Build and test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        perl-version:
          - '5.30'
          - '5.32'
          - 'latest'
          - 'threaded'

    container:
      image: perl:${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@v2
      - name: Configure
        run: perl Makefile.PL
      - name: Build
        run: make
      - name: Test
        run: make test
      - name: Report coverage
        continue-on-error: true
        run: |
          cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Codecov
          cpanm --quiet --installdeps --notest .
          cover -test
          cover -report codecov
        env:
          CODECOV_TOKEN: $${{ secrets.CODECOV_TOKEN }}
